jest.mock('server-only',()=>({}),{virtual:true});
jest.mock('@/lib/firebaseAdmin',()=>({getInstitutionalAdminDb:()=>{throw new Error('LIVE_FORBIDDEN');}}));
import { executeInstitutionalLifecycle } from '../src/services/institutionalLifecycleBoundary';
import { adminFixture } from './helpers/p8InstitutionalAdminFixture';
import { readFileSync } from 'fs';
const now=1800000000000;
function fixture(){const project={estado:'EN REVISIÓN',createdBy:'historical',numeroExpediente:'PPC-original',canonicalGeography:{type:'CORRIDOR',geometry:{type:'LineString',coordinates:[[1,2],[3,4]]}},findings:[{id:'f1'}]};const f=adminFixture({'projects/A':project,'projects/A/photos/p':{id:'p'},'projects/A/documents/d':{id:'d'}});const identity=jest.fn(async()=>({institutionalUserId:'1',username:'PG supervisor',role:'ADMIN' as const}));const grant=jest.fn(async()=>({projectId:'A',institutionalUserId:'1',relation:'ASSIGNED',allowedActions:['WRITE'],revokedAt:null}));return {...f,project,identity,grant,deps:{identity,grant:grant as any,database:()=>f.db,now:()=>now}};}
const input:any={projectId:'A',entityId:'A',kind:'PROJECT',operation:'REVIEW_CLOSE',operationId:'close',reason:'Human checklist completed'};
test('administrative close preserves historic contents and binds server actor/audit',async()=>{const f=fixture();const result=await executeInstitutionalLifecycle('fixture',input,f.deps);expect(result.status).toBe('COMPLETED');expect(f.get('projects/A')).toMatchObject({...f.project,estado:'CERRADO',evaluadoPor:'PG supervisor',fechaEvaluacion:now});expect(f.get('projects/A/photos/p')).toEqual({id:'p'});expect(f.get('projects/A/documents/d')).toEqual({id:'d'});expect(f.entries().find(([p])=>p.startsWith('audit_logs/'))![1]).toMatchObject({action:'REVIEW_CLOSE',actorInstitutionalUserId:'1'});expect(f.entries().filter(([p])=>p.includes('reportCertifications')||p.includes('reportPublications'))).toHaveLength(0);});
test('return preserves legacy feedback/deadline fields with server identity/time',async()=>{const f=fixture();await executeInstitutionalLifecycle('fixture',{...input,operation:'REVIEW_RETURN',returnDeadlineHours:48},f.deps);expect(f.get('projects/A')).toMatchObject({estado:'DEVUELTO',comentariosAuditoria:input.reason,comentariosSupervisor:input.reason,deadlineAt:now+48*3600000,devueltoPor:'PG supervisor'});});
test('same close retry is idempotent after state becomes closed',async()=>{const f=fixture();await executeInstitutionalLifecycle('fixture',input,f.deps);const before=f.entries();await executeInstitutionalLifecycle('fixture',input,f.deps);expect(f.entries()).toEqual(before);});
test.each(['USER','missing-grant','revoked','wrong-project'])('authority denial %s does not mutate project',async mode=>{const f=fixture();if(mode==='USER')f.identity.mockResolvedValue({institutionalUserId:'1',username:'fake admin',role:'USER'} as any);if(mode==='missing-grant')f.grant.mockResolvedValue(null as any);if(mode==='revoked')f.grant.mockResolvedValue({...await f.grant(),revokedAt:new Date(now-1)} as any);if(mode==='wrong-project')f.grant.mockResolvedValue({...await f.grant(),projectId:'B'});const before=f.entries();await expect(executeInstitutionalLifecycle('fixture',input,f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('audit failure rolls back administrative review state',async()=>{const f=fixture();f.failWrite('audit_logs/');const before=f.entries();await expect(executeInstitutionalLifecycle('fixture',input,f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test.each([0,169,NaN,1.5])('invalid return deadline %# fails closed',async hours=>{const f=fixture();await expect(executeInstitutionalLifecycle('fixture',{...input,operation:'REVIEW_RETURN',returnDeadlineHours:hours},f.deps)).rejects.toThrow('DEADLINE_INVALID');expect(f.get('projects/A')).toEqual(f.project);});
test('archived parent cannot be closed through administrative review',async()=>{const f=fixture();f.seed('projects/A',{...f.project,estado:'ARCHIVADO'});await expect(executeInstitutionalLifecycle('fixture',input,f.deps)).rejects.toThrow('INACCESSIBLE');});
test('active admin handlers use lifecycle action rather than protected client state writes',()=>{const source=readFileSync('src/app/admin/page.tsx','utf8');const region=source.slice(source.indexOf('const handleValidar ='),source.indexOf('const expedientesPendientes ='));expect(region).toContain('operation:"REVIEW_CLOSE"');expect(region).toContain('operation:"REVIEW_RETURN"');expect(region).not.toContain('updateDoc(');expect(region).not.toContain('evaluadoPor: user');});
