jest.mock('server-only',()=>({}),{virtual:true});
jest.mock('@/lib/firebaseAdmin',()=>({getInstitutionalAdminDb:()=>{throw new Error('REAL_ADAPTER_FORBIDDEN');}}));
import { mutateInstitutionalGang } from '../src/services/institutionalGangBoundary';
import { executeInstitutionalImfo } from '../src/services/institutionalImfoBoundary';
import { adminFixture } from './helpers/p8InstitutionalAdminFixture';
function fixture(){const f=adminFixture({'projects/A':{deleted:false,estado:'ABIERTO'},'pandillas/g':{projectId:'A',createdBy:'historical',createdAt:1},'imfo_sources/s':{name:'Server source',operationalStatus:'Pendiente Autorización'}});const actor={institutionalUserId:'1',username:'server-actor',role:'USER' as const};return {...f,actor,authorize:jest.fn(async()=>({allowed:true,actor,projectId:'A'} as any)),identity:jest.fn(async()=>actor)};}
const input:any={operation:'SAVE',projectId:'A',id:'g',data:{projectId:'A',nombre:'Gang',createdBy:'forged',createdAt:99,updatedBy:'forged'}};
test('gang writes bind server actor and preserve historical attribution',async()=>{const f=fixture();await mutateInstitutionalGang('session',input,{authorize:f.authorize,database:()=>f.db});expect(f.get('pandillas/g').createdBy).toBe('historical');expect(f.get('pandillas/g').createdAt).toBe(1);expect(f.get('pandillas/g').updatedBy).toBe('server-actor');expect(f.entries().find(([path])=>path.startsWith('audit_logs/'))![1].actorInstitutionalUserId).toBe('1');});
test.each(['MISSING','REVOKED','PG_UNAVAILABLE'])('gang authority failure %s denies before IO',async()=>{const f=fixture();f.authorize.mockResolvedValue({allowed:false} as any);const database=jest.fn();await expect(mutateInstitutionalGang('session',input,{authorize:f.authorize,database})).rejects.toThrow('ACCESS_DENIED');expect(database).not.toHaveBeenCalled();});
test('gang cross project collision cannot mutate or delete',async()=>{const f=fixture();f.seed('pandillas/g',{projectId:'B'});await expect(mutateInstitutionalGang('session',input,{authorize:f.authorize,database:()=>f.db})).rejects.toThrow('CROSS_PROJECT');});
test('gang audit failure rolls back save',async()=>{const f=fixture();const before=f.entries();f.failWrite('audit_logs/');await expect(mutateInstitutionalGang('session',input,{authorize:f.authorize,database:()=>f.db})).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('unassociated gang requires explicit project',async()=>{const f=fixture();await expect(mutateInstitutionalGang('session',{...input,projectId:undefined},{authorize:f.authorize,database:()=>f.db})).rejects.toThrow('INPUT_INVALID');expect(f.authorize).not.toHaveBeenCalled();});
test('IMFO actor failure denies before Admin IO',async()=>{const f=fixture();f.identity.mockRejectedValue(new Error('IDENTITY_REVOKED'));const database=jest.fn();await expect(executeInstitutionalImfo('session','READ',{}, {identity:f.identity,database})).rejects.toThrow();expect(database).not.toHaveBeenCalled();});
test.each(['UPDATE','DELETE','AUTHORIZE'] as const)('ordinary user cannot %s global catalogue',async operation=>{const f=fixture();const database=jest.fn();await expect(executeInstitutionalImfo('session',operation,{id:'s',data:{}},{identity:f.identity,database})).rejects.toThrow();expect(database).not.toHaveBeenCalled();});
test('ADMIN does not bypass explicit SUPER_ADMIN catalogue authorization',async()=>{const f=fixture();f.identity.mockResolvedValue({...f.actor,role:'ADMIN'} as any);await expect(executeInstitutionalImfo('session','AUTHORIZE',{id:'s'},{identity:f.identity,database:()=>f.db})).rejects.toThrow('SUPER_ADMIN_REQUIRED');});
test('discovery forcibly remains pending despite fabricated Active state',async()=>{const f=fixture();await executeInstitutionalImfo('session','DISCOVER',{id:'new',data:{name:'Discovered',operationalStatus:'Activa'}},{identity:f.identity,database:()=>f.db});expect(f.get('imfo_sources/new').operationalStatus).toBe('Pendiente Autorización');});
test('learning observation and metrics audit roll back together',async()=>{const f=fixture();const before=f.entries();f.failWrite('audit_logs/');await expect(executeInstitutionalImfo('session','LEARNING',{id:'s',responseTimeMs:10,resultCount:2,success:true},{identity:f.identity,database:()=>f.db})).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('empty catalogue never seeds or fabricates authorized sources',async()=>{const f=adminFixture();const actor=fixture().actor;expect(await executeInstitutionalImfo('session','READ',{}, {identity:async()=>actor,database:()=>f.db})).toEqual([]);expect(f.entries()).toEqual([]);});
