jest.mock('server-only',()=>({}),{virtual:true});
jest.mock('firebase-admin/firestore',()=>({FieldValue:{serverTimestamp:()=> 'SERVER_TIME'}}));
jest.mock('@/lib/firebaseAdmin',()=>({getInstitutionalAdminDb:()=>{throw new Error('REAL_FORBIDDEN');}}));
import { executeInstitutionalSweep } from '../src/services/geoint/institutionalSweepBoundary';
import { adminFixture } from './helpers/p8InstitutionalAdminFixture';
function fixture(){const f=adminFixture({'projects/A':{deleted:false,estado:'ABIERTO',sweeps:[]}});const authorize=jest.fn(async()=>({allowed:true,projectId:'A',actor:{institutionalUserId:'1',username:'Server actor',role:'USER'}} as any));return{...f,authorize,deps:{authorize,database:()=>f.db}};}
const proposal:any={id:'sweep',engine:'OSINT',source:'Fixture',type:'Indirecta',status:'CERTIFIED',traceabilityId:'trace',lifecycle:{status:'CERTIFIED',validatedBy:'forged'}};
test('registration reconstructs lifecycle and atomically commits entity/outbox/fingerprint/audit',async()=>{const f=fixture();const records=await executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps);expect(records[0].lifecycle.status).toBe('RUNNING');expect(records[0].humanValidationStatus).toBe('UNREVIEWED');expect(records[0].status).toBe('Pendiente');expect(f.entries().filter(([path])=>path.startsWith('geoint_event_outbox/'))).toHaveLength(2);expect(f.entries().filter(([path])=>path.startsWith('audit_logs/'))).toHaveLength(2);});
test.each(['audit_logs/','geoint_event_outbox/','geoint_event_fingerprints/','projects/A'])('failure in %s rolls back entity and event transport',async path=>{const f=fixture();const before=f.entries();f.failWrite(path);await expect(executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('fresh grant failure denies before persistence',async()=>{const f=fixture();f.authorize.mockResolvedValue({allowed:false} as any);const database=jest.fn();await expect(executeInstitutionalSweep('session','A','REGISTER',proposal,{authorize:f.authorize,database})).rejects.toThrow('ACCESS_DENIED');expect(database).not.toHaveBeenCalled();});
test('human approval uses existing engine and binds fresh institutional actor',async()=>{const f=fixture();const records=await executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps);const updated=await executeInstitutionalSweep('session','A','UPDATE',{...records[0],status:'Integrado',expectedVersion:records[0].lifecycle.version,validatedBy:'forged'},f.deps);expect(updated[0].lifecycle.status).toBe('CERTIFIED');expect(updated[0].validatedBy.id).toBe('1');expect(updated[0].validationSource).toBe('ADR_020_24_HUMAN_ACTION');});
test('stale version cannot promote a human state',async()=>{const f=fixture();await executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps);await expect(executeInstitutionalSweep('session','A','UPDATE',{...proposal,status:'Integrado',expectedVersion:0},f.deps)).rejects.toThrow('VERSION_CONFLICT');});
test('stored sweep from another project cannot be approved',async()=>{const f=fixture();f.seed('projects/A',{sweeps:[{id:'sweep',lifecycle:{expedienteId:'B',version:1}}]});await expect(executeInstitutionalSweep('session','A','UPDATE',{...proposal,expectedVersion:1},f.deps)).rejects.toThrow('CROSS_PROJECT');});

test('non-transition sweep edit still creates immutable mutation audit/outbox',async()=>{const f=fixture();const records=await executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps);const before=f.entries().filter(([path])=>path.startsWith('audit_logs/')).length;await executeInstitutionalSweep('session','A','UPDATE',{...records[0],data:'changed output',expectedVersion:records[0].lifecycle.version},f.deps);expect(f.entries().filter(([path])=>path.startsWith('audit_logs/'))).toHaveLength(before+1);expect(f.entries().filter(([path])=>path.startsWith('geoint_event_outbox/')).length).toBeGreaterThan(2);});
test('certified sweep contents cannot change while retaining old human approval',async()=>{const f=fixture();const records=await executeInstitutionalSweep('session','A','REGISTER',proposal,f.deps);const certified=await executeInstitutionalSweep('session','A','UPDATE',{...records[0],status:'Integrado',expectedVersion:records[0].lifecycle.version},f.deps);const before=f.entries();await expect(executeInstitutionalSweep('session','A','UPDATE',{...certified[0],data:'changed certified contents',expectedVersion:certified[0].lifecycle.version},f.deps)).rejects.toThrow('CERTIFIED_IMMUTABLE');expect(f.entries()).toEqual(before);});
