jest.mock('server-only',()=>({}),{virtual:true});
jest.mock('firebase-admin/firestore',()=>({FieldValue:{serverTimestamp:()=> 'SERVER_TIME'}}));
jest.mock('@/lib/firebaseAdmin',()=>({getInstitutionalAdminDb:()=>{throw new Error('REAL_FORBIDDEN');}}));
jest.mock('@/lib/firebase',()=>({getDb:()=>{throw new Error('CLIENT_IO_FORBIDDEN');}}));
jest.mock('@/lib/firebaseServer',()=>({getFirebaseServerDb:()=>{throw new Error('CLIENT_IO_FORBIDDEN');}}));
import { executeInstitutionalGeointEntity } from '../src/services/institutionalGeointEntityBoundary';
import { adminFixture } from './helpers/p8InstitutionalAdminFixture';
import { GeointGovernanceStatus } from '../src/types/geointGovernance';
function fixture(){const f=adminFixture({'projects/A':{deleted:false,estado:'ABIERTO'}});const authorize=jest.fn(async()=>({allowed:true,projectId:'A',actor:{institutionalUserId:'1',username:'Server actor',role:'USER'}} as any));return{...f,authorize,deps:{authorize,database:()=>f.db}};}
const geographic:any={projectId:'A',kind:'GEOGRAPHIC',operation:'SAVE',id:'geo',data:{projectId:'A',lat:21.88,lng:-102.29,type:'VERTEX',source:'HUMAN_MAP_VERTEX',geometryType:'lineal',createdBy:'forged',createdAt:100}};
const street:any={projectId:'A',kind:'STREETVIEW',operation:'SAVE',id:'finding',data:{expedienteId:'A',traceabilityId:'trace-finding',sourceEvidenceId:'capture',captureId:'capture',geographyId:'geo',lineageStatus:'SUPPORTED',categoria:'RUTA_ACCESO',coordenadas:{lat:21.88,lng:-102.29},imagen:'https://fixture.test/image',estado:GeointGovernanceStatus.APPROVED_EVIDENCE,validatedBy:'forged'}};
test('geographic entity/outbox/fingerprint/audit commit atomically with server identity',async()=>{const f=fixture();const result=await executeInstitutionalGeointEntity('session',geographic,f.deps);expect(result.createdBy).toBe('user:1');expect(f.get('projects/A/geographicEntities/geo')).toBeDefined();for(const root of ['audit_logs/','geoint_event_outbox/','geoint_event_fingerprints/'])expect(f.entries().filter(([path])=>path.startsWith(root))).toHaveLength(1);});
test.each(['audit_logs/','geoint_event_outbox/','geoint_event_fingerprints/','geographicEntities/'])('entity failure in %s rolls back every business/transport write',async path=>{const f=fixture();const before=f.entries();f.failWrite(path);await expect(executeInstitutionalGeointEntity('session',geographic,f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('same geographic upsert retries without duplicated canonical event or audit',async()=>{const f=fixture();await executeInstitutionalGeointEntity('session',geographic,f.deps);const before=f.entries();await executeInstitutionalGeointEntity('session',geographic,f.deps);expect(f.entries()).toEqual(before);});
test('grant revocation denies entity mutation before Admin IO',async()=>{const f=fixture();f.authorize.mockResolvedValue({allowed:false} as any);const database=jest.fn();await expect(executeInstitutionalGeointEntity('session',geographic,{authorize:f.authorize,database})).rejects.toThrow('ACCESS_DENIED');expect(database).not.toHaveBeenCalled();});
test('StreetView creation cannot self-approve from client state',async()=>{const f=fixture();const result=await executeInstitutionalGeointEntity('session',street,f.deps);expect(result.estado).toBe(GeointGovernanceStatus.PENDING_REVIEW);expect(result.validatedBy).toBeUndefined();expect(result.createdBy).toBe('Server actor');expect(f.get('streetview_findings/finding')).toEqual(f.get('projects/A/streetview_findings/finding'));});
test('fresh StreetView approval reuses traceability engine and binds PG actor',async()=>{const f=fixture();await executeInstitutionalGeointEntity('session',street,f.deps);const result=await executeInstitutionalGeointEntity('session',{...street,operation:'UPDATE',data:{estado:GeointGovernanceStatus.APPROVED_EVIDENCE,validatedBy:'forged',validationComment:'Human review'}},f.deps);expect(result.estado).toBe(GeointGovernanceStatus.APPROVED_EVIDENCE);expect(result.validatedBy.id).toBe('1');expect(result.usuarioRevision).toBe('Server actor');});
test('root mirror collision cannot overwrite a different project finding',async()=>{const f=fixture();f.seed('streetview_findings/finding',{expedienteId:'B'});await expect(executeInstitutionalGeointEntity('session',street,f.deps)).rejects.toThrow('CROSS_PROJECT');expect(f.get('projects/A/streetview_findings/finding')).toBeUndefined();});
test('mirror write failure cannot report successful creation',async()=>{const f=fixture();const before=f.entries();f.failWrite('streetview_findings/finding');await expect(executeInstitutionalGeointEntity('session',street,f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('geographic delete rolls back if audit persistence fails',async()=>{const f=fixture();await executeInstitutionalGeointEntity('session',geographic,f.deps);const before=f.entries();f.failWrite('audit_logs/');await expect(executeInstitutionalGeointEntity('session',{...geographic,operation:'DELETE'},f.deps)).rejects.toThrow();expect(f.entries()).toEqual(before);});
test('missing real coordinates cannot produce fabricated entity success',async()=>{const f=fixture();await expect(executeInstitutionalGeointEntity('session',{...geographic,data:{...geographic.data,lat:null}},f.deps)).rejects.toThrow('GEOGRAPHY_INVALID');expect(f.entries()).toHaveLength(1);});

test('successive entity edits each bind a new event/audit and invalidate source revision',async()=>{const f=fixture();await executeInstitutionalGeointEntity('session',geographic,f.deps);await executeInstitutionalGeointEntity('session',{...geographic,operation:'UPDATE',data:{metadata:{comment:'one'}}},f.deps);await executeInstitutionalGeointEntity('session',{...geographic,operation:'UPDATE',data:{metadata:{comment:'two'}}},f.deps);expect(f.entries().filter(([path])=>path.startsWith('audit_logs/'))).toHaveLength(3);expect(f.entries().filter(([path])=>path.startsWith('geoint_event_outbox/'))).toHaveLength(3);expect(f.get('projects/A').institutionalSourceRevision).toBe(3);});
test('upsert preserves historical geographic attribution',async()=>{const f=fixture();f.seed('projects/A/geographicEntities/geo',{...geographic.data,createdBy:'historical-author',createdAt:50});await executeInstitutionalGeointEntity('session',geographic,f.deps);expect(f.get('projects/A/geographicEntities/geo').createdBy).toBe('historical-author');expect(f.get('projects/A/geographicEntities/geo').createdAt).toBe(50);});
