jest.mock('server-only', () => ({}), { virtual: true });
jest.mock('@/lib/firebaseAdmin', () => ({ getInstitutionalAdminDb: jest.fn(() => { throw new Error('REAL_ADAPTER_NOT_ALLOWED'); }) }));
import { executeInstitutionalLifecycle, type LifecycleRequest } from '../src/services/institutionalLifecycleBoundary';
import { adminFixture } from './helpers/p8InstitutionalAdminFixture';
const now = 1800000000000;
function fixture() {
 const store = adminFixture({ 'projects/A': { name: 'A', deleted: false, estado: 'ABIERTO', photoCount: 1, numeroExpediente: 'PPC-unchanged', createdBy: 'historical' }, 'projects/A/photos/p': { tipo: 'FIELD_CAPTURE', url: 'must-not-appear-in-audit', createdAt: 100 } });
 let time = now;
 const identity = jest.fn(async () => ({ institutionalUserId: '1', username: 'fixture', role: 'ADMIN' as const }));
 const grant = jest.fn(async () => ({ projectId: 'A', institutionalUserId: '1', relation: 'ASSIGNED', allowedActions: ['WRITE'], revokedAt: null }));
 const database = jest.fn(() => store.db);
 return { ...store, identity, grant, database, time: (value: number) => { time = value; }, deps: { identity, grant: grant as any, database, now: () => time } };
}
const input: LifecycleRequest = { projectId: 'A', entityId: 'p', kind: 'PHOTO', operation: 'DELETE', operationId: 'op-delete', reason: 'Explicit institutional deletion' };
test('delete, count and both immutable audits commit atomically with server actor', async () => { const f = fixture(); const result = await executeInstitutionalLifecycle('session',input,f.deps); expect(result.status).toBe('COMPLETED'); expect(f.get('projects/A/photos/p')).toBeUndefined(); expect(f.get('projects/A').photoCount).toBe(0); const imageAudit = f.entries().find(([path]) => path.startsWith('image_deletion_logs/'))![1]; expect(imageAudit.deletedBy).toBe('fixture'); expect(imageAudit).not.toHaveProperty('url'); expect(f.entries().filter(([path]) => path.startsWith('audit_logs/'))).toHaveLength(1); });
test.each(['audit_logs/','image_deletion_logs/','institutionalLifecycleOperations/','projects/A'])('failure in %s rolls back delete and audit', async path => { const f = fixture(); const before = f.entries(); f.failWrite(path); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow(); expect(f.entries()).toEqual(before); });
test('commit failure cannot be recognized as successful', async () => { const f = fixture(); const before = f.entries(); f.failCommit(true); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow(); expect(f.entries()).toEqual(before); });
test('invalid institutional actor fails before persistence', async () => { const f = fixture(); f.identity.mockRejectedValueOnce(new Error('ACTOR_INVALID')); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow(); expect(f.database).not.toHaveBeenCalled(); });
test('missing grant denies ADMIN', async () => { const f = fixture(); f.grant.mockResolvedValueOnce(null as any); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow('GRANT_REQUIRED'); expect(f.database).not.toHaveBeenCalled(); });
test('revoked grant denies SUPER_ADMIN', async () => { const f = fixture(); f.identity.mockResolvedValueOnce({ institutionalUserId: '1', username: 'fixture', role: 'SUPER_ADMIN' } as any); f.grant.mockResolvedValueOnce({ projectId: 'A', institutionalUserId: '1', relation: 'ASSIGNED', allowedActions: ['WRITE'], revokedAt: new Date(now-1) } as any); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow('ACCESS_DENIED'); expect(f.database).not.toHaveBeenCalled(); });
test('wrong grant project denies', async () => { const f = fixture(); f.grant.mockResolvedValueOnce({ projectId: 'B', institutionalUserId: '1', relation: 'ASSIGNED', allowedActions: ['WRITE'], revokedAt: null }); await expect(executeInstitutionalLifecycle('session',input,f.deps)).rejects.toThrow(); expect(f.database).not.toHaveBeenCalled(); });
test('another project analysis cannot be deleted', async () => { const f = fixture(); f.seed('analyses/x',{ projectId: 'B' }); await expect(executeInstitutionalLifecycle('session',{ ...input, kind: 'ANALYSIS', entityId: 'x' },f.deps)).rejects.toThrow('CROSS_PROJECT'); expect(f.get('analyses/x')).toEqual({ projectId: 'B' }); });
test('same operation retry does not duplicate audit or decrement twice', async () => { const f = fixture(); await executeInstitutionalLifecycle('session',input,f.deps); const before = f.entries(); await executeInstitutionalLifecycle('session',input,f.deps); expect(f.entries()).toEqual(before); });
test('same operation ID with different payload is denied', async () => { const f = fixture(); await executeInstitutionalLifecycle('session',input,f.deps); await expect(executeInstitutionalLifecycle('session',{ ...input,reason: 'changed' },f.deps)).rejects.toThrow('RETRY_CONFLICT'); });
async function trashFixture() { const f = fixture(); await executeInstitutionalLifecycle('session',{ ...input, operation: 'SOFT_DELETE', operationId: 'soft' },f.deps); const [path] = f.entries().find(([path]) => path.startsWith('trash/'))!; return { ...f, trashId: path.split('/')[1] }; }
test('soft delete and restore preserve attribution, folio and original contents', async () => { const f = await trashFixture(); expect(f.get('projects/A/photos/p').deleted).toBe(true); await executeInstitutionalLifecycle('session',{ ...input, operation: 'RESTORE', operationId: 'restore', trashId: f.trashId },f.deps); expect(f.get('projects/A/photos/p').deleted).toBe(false); expect(f.get('projects/A').numeroExpediente).toBe('PPC-unchanged'); expect(f.get('projects/A').createdBy).toBe('historical'); expect(f.get('trash/'+f.trashId)).toBeUndefined(); });
test('tampered trash path cannot restore cross-project', async () => { const f = await trashFixture(); const path = 'trash/'+f.trashId; f.seed(path,{ ...f.get(path), originalPath: 'projects/B/photos/p' }); const before = f.entries(); await expect(executeInstitutionalLifecycle('session',{ ...input, operation: 'RESTORE', operationId: 'restore', trashId: f.trashId },f.deps)).rejects.toThrow('CROSS_PROJECT'); expect(f.entries()).toEqual(before); });
test('purge requires retention expiry', async () => { const f = await trashFixture(); await expect(executeInstitutionalLifecycle('session',{ ...input, operation: 'PURGE', operationId: 'purge', trashId: f.trashId },f.deps)).rejects.toThrow('RETENTION_GATE'); });
test('expired trash can be purged by ADMIN with explicit WRITE', async () => { const f = await trashFixture(); f.time(now+7*24*60*60*1000); await executeInstitutionalLifecycle('session',{ ...input, operation: 'PURGE', operationId: 'purge', trashId: f.trashId },f.deps); expect(f.get('projects/A/photos/p')).toBeUndefined(); expect(f.get('trash/'+f.trashId)).toBeUndefined(); });
test('USER cannot purge even with WRITE', async () => { const f = await trashFixture(); f.identity.mockResolvedValue({ institutionalUserId: '1', username: 'fixture', role: 'USER' } as any); await expect(executeInstitutionalLifecycle('session',{ ...input, operation: 'PURGE', operationId: 'purge', trashId: f.trashId },f.deps)).rejects.toThrow('ADMIN_REQUIRED'); });
test('archive and reactivate require grant and bind server attribution', async () => { const f = fixture(); const project: LifecycleRequest = { ...input,entityId:'A',kind:'PROJECT',operation:'ARCHIVE',operationId:'archive' }; await executeInstitutionalLifecycle('session',project,f.deps); expect(f.get('projects/A').estado).toBe('ARCHIVADO'); await executeInstitutionalLifecycle('session',{ ...project, operation:'REACTIVATE',operationId:'reactivate' },f.deps); expect(f.get('projects/A').estado).toBe('ABIERTO'); expect(f.get('projects/A').reactivatedBy).toBe('fixture'); });

test('Storage failure leaves audited pending intent and no success receipt',async()=>{const f=fixture();f.seed('projects/A/photos/p',{storagePath:'projects/A/p.jpg'});const deleteObject=jest.fn(async()=>{throw new Error('STORAGE_FAILURE');});await expect(executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject})).rejects.toThrow('STORAGE_FAILURE');expect(f.get('projects/A/photos/p').lifecycleDeletionPending).toBeTruthy();expect(f.entries().filter(([path])=>path.startsWith('institutionalLifecycleOperations/'))).toHaveLength(0);expect(f.entries().filter(([path])=>path.startsWith('image_deletion_logs/'))).toHaveLength(0);expect(f.entries().filter(([path])=>path.startsWith('audit_logs/intent-'))).toHaveLength(1);});
test('intent audit failure preserves entity and does not call Storage',async()=>{const f=fixture();f.seed('projects/A/photos/p',{storagePath:'projects/A/p.jpg'});f.failWrite('audit_logs/intent-');const deleteObject=jest.fn(async()=>{});const before=f.entries();await expect(executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject})).rejects.toThrow();expect(f.entries()).toEqual(before);expect(deleteObject).not.toHaveBeenCalled();});
test('Storage deletion and retry complete the same intent without duplicate audit',async()=>{const f=fixture();f.seed('projects/A/photos/p',{storagePath:'projects/A/p.jpg'});const deleteObject=jest.fn().mockRejectedValueOnce(new Error('STORAGE_FAILURE')).mockResolvedValue(undefined);await expect(executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject})).rejects.toThrow();await executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject});const before=f.entries();await executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject});expect(f.entries()).toEqual(before);expect(deleteObject).toHaveBeenCalledTimes(2);expect(f.entries().find(([path])=>path.startsWith('institutionalDeletionIntents/'))![1].status).toBe('COMPLETED');});
test('revocation after Storage prevents final deletion and success audit',async()=>{const f=fixture();f.seed('projects/A/photos/p',{storagePath:'projects/A/p.jpg'});const deleteObject=jest.fn(async()=>{f.grant.mockResolvedValue({projectId:'A',institutionalUserId:'1',relation:'ASSIGNED',allowedActions:['WRITE'],revokedAt:new Date(now)} as any);});await expect(executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject})).rejects.toThrow('ACCESS_DENIED');expect(f.get('projects/A/photos/p')).toBeDefined();expect(f.entries().filter(([path])=>path.startsWith('image_deletion_logs/'))).toHaveLength(0);});
test('cross project Storage path denies without intent or external deletion',async()=>{const f=fixture();f.seed('projects/A/photos/p',{storagePath:'projects/B/p.jpg'});const deleteObject=jest.fn(async()=>{});const before=f.entries();await expect(executeInstitutionalLifecycle('session',input,{...f.deps,deleteObject})).rejects.toThrow('STORAGE_CROSS_PROJECT');expect(f.entries()).toEqual(before);expect(deleteObject).not.toHaveBeenCalled();});

test('deletion atomically invalidates live evidence references and source revision',async()=>{const f=fixture();f.seed('projects/A',{deleted:false,estado:'ABIERTO',photoCount:1,album:[{id:'p'},{id:'other'}],photoEvidence:[{sourceEvidenceId:'p'}],findings:[{findingId:'linked',evidenceIds:['p']},{findingId:'independent',evidenceIds:['other']}],analysisOutputs:[{supportingEvidenceIds:['p']}],geographicEntities:[{photoId:'p'}]});await executeInstitutionalLifecycle('session',input,f.deps);const project=f.get('projects/A');expect(project.album).toEqual([{id:'other'}]);expect(project.photoEvidence).toEqual([]);expect(project.findings).toEqual([{findingId:'independent',evidenceIds:['other']}]);expect(project.analysisOutputs).toEqual([]);expect(project.geographicEntities).toEqual([]);expect(project.institutionalSourceRevision).toBe(1);expect(project.deletedEvidenceIds).toContain('p');});
