export const INSTITUTIONAL_ISSUER = "SECRETARÍA DE SEGURIDAD PÚBLICA DEL ESTADO DE AGUASCALIENTES";
export const INSTITUTIONAL_UNIT = "CEIPOL";
export const EXECUTIVE_GEOINT_OFFICIAL_TITLE = "INFORME EJECUTIVO GEOINT";
export const TECHNICAL_ANNEX_OFFICIAL_TITLE = "ANEXO TÉCNICO";
